import type { School, Department, Suggestion, FAQ, User } from './types';

// Mock Schools
export const mockSchools: School[] = [
  { id: '1', name: 'Trường THPT Huỳnh Thúc Kháng', district: 'TP Vinh', level: 'Trung học' },
  { id: '2', name: 'Trường THCS Quang Trung', district: 'TP Vinh', level: 'Trung học' },
  { id: '3', name: 'Trường Tiểu học Lê Lợi', district: 'Cửa Lò', level: 'Tiểu học' },
  { id: '4', name: 'Trường Mầm non Hoa Mai', district: 'Diễn Châu', level: 'Mầm non' },
  { id: '5', name: 'Trường THPT Phan Đăng Lưu', district: 'Nghĩa Đàn', level: 'Trung học' },
  { id: '6', name: 'Trường THCS Nam Đàn', district: 'Nam Đàn', level: 'Trung học' },
  { id: '7', name: 'Trường Tiểu học Quỳnh Lưu', district: 'Quỳnh Lưu', level: 'Tiểu học' },
  { id: '8', name: 'Trường Mầm non Hướng Dương', district: 'Yên Thành', level: 'Mầm non' },
];

// Mock Departments
export const mockDepartments: Department[] = [
  { id: 'dept1', name: 'Phòng Giáo dục Mầm non', code: 'GDMN' },
  { id: 'dept2', name: 'Phòng Giáo dục Tiểu học', code: 'GDTH' },
  { id: 'dept3', name: 'Phòng Giáo dục Trung học', code: 'GDTHPT' },
  { id: 'dept4', name: 'Phòng Quản lý Chất lượng', code: 'QLCL' },
  { id: 'dept5', name: 'Văn phòng và Truyền thông', code: 'VPTT' },
  { id: 'dept6', name: 'Phòng Tài chính và Đầu tư', code: 'TCDT' },
  { id: 'dept7', name: 'Phòng Tổ chức Cán bộ', code: 'TCCB' },
  { id: 'dept8', name: 'Phòng Giáo dục Thường xuyên - Nghề nghiệp', code: 'GDTX' },
];

// Mock Categories
export const mockCategories = [
  'Cơ sở vật chất',
  'Nhân sự',
  'Chuyên môn',
  'Tài chính',
  'Chế độ chính sách',
  'Thi cử',
  'Học sinh',
  'Khác',
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Nguyễn Văn A',
    role: 'school',
    email: 'nguyenvana@school1.edu.vn',
    schoolId: '1',
    schoolName: 'Trường THPT Huỳnh Thúc Kháng',
  },
  {
    id: 'user2',
    name: 'Trần Thị B',
    role: 'department-leader',
    email: 'tranthib@sone.gov.vn',
    departmentId: 'dept3',
    departmentName: 'Phòng Giáo dục Trung học',
  },
  {
    id: 'user3',
    name: 'Lê Văn C',
    role: 'specialist',
    email: 'levanc@sone.gov.vn',
    departmentId: 'dept3',
    departmentName: 'Phòng Giáo dục Trung học',
  },
  {
    id: 'user4',
    name: 'Phạm Thị D',
    role: 'office',
    email: 'phamthid@sone.gov.vn',
    departmentId: 'dept5',
    departmentName: 'Văn phòng và Truyền thông',
  },
  {
    id: 'user5',
    name: 'Hoàng Văn E',
    role: 'director',
    email: 'hoangvane@sone.gov.vn',
  },
  {
    id: 'user6',
    name: 'Ngô Thị F',
    role: 'principal',
    email: 'ngothif@school1.edu.vn',
    schoolId: '1',
    schoolName: 'Trường THPT Huỳnh Thúc Kháng',
  },
];

// Mock Suggestions
export const mockSuggestions: Suggestion[] = [
  {
    id: 'sug1',
    title: 'Kiến nghị về chế độ phụ cấp cho giáo viên vùng khó khăn',
    content: 'Đề nghị Sở xem xét và điều chỉnh mức phụ cấp cho giáo viên công tác tại các xã vùng khó khăn theo quy định mới.',
    type: 'sensitive',
    status: 'processing',
    category: 'Chế độ chính sách',
    schoolId: '1',
    schoolName: 'Trường THPT Huỳnh Thúc Kháng',
    departmentId: 'dept7',
    departmentName: 'Phòng Tổ chức Cán bộ',
    createdBy: 'user1',
    createdByName: 'Ẩn danh',
    createdAt: '2026-02-20T10:30:00Z',
    updatedAt: '2026-02-25T14:20:00Z',
    assignedTo: 'user3',
    assignedToName: 'Lê Văn C',
    isAnonymous: true,
    priority: 'high',
    dueDate: '2026-03-05',
  },
  {
    id: 'sug2',
    title: 'Đề nghị hỗ trợ kinh phí sửa chữa phòng học',
    content: 'Trường có 3 phòng học bị hư hỏng nặng do mưa bão, cần hỗ trợ kinh phí khẩn cấp để sửa chữa trước khi học sinh trở lại.',
    type: 'sensitive',
    status: 'completed',
    category: 'Cơ sở vật chất',
    schoolId: '2',
    schoolName: 'Trường THCS Quang Trung',
    departmentId: 'dept6',
    departmentName: 'Phòng Tài chính và Đầu tư',
    createdBy: 'user1',
    createdByName: 'Ẩn danh',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-15T16:30:00Z',
    assignedTo: 'user3',
    assignedToName: 'Nguyễn Văn X',
    response: 'Đã phê duyệt kinh phí 200 triệu đồng cho việc sửa chữa. Vui lòng liên hệ phòng Tài chính để hoàn thiện hồ sơ.',
    isAnonymous: true,
    rating: 5,
    ratingComment: 'Rất hài lòng với tốc độ xử lý',
    priority: 'high',
  },
  {
    id: 'sug3',
    title: 'Hỏi về quy trình tổ chức thi học sinh giỏi cấp tỉnh',
    content: 'Đề nghị được hướng dẫn chi tiết về quy trình đăng ký, nộp hồ sơ và tổ chức thi HSG cấp tỉnh năm 2026.',
    type: 'non-sensitive',
    status: 'pending',
    category: 'Thi cử',
    schoolId: '3',
    schoolName: 'Trường Tiểu học Lê Lợi',
    departmentId: 'dept2',
    departmentName: 'Phòng Giáo dục Tiểu học',
    createdBy: 'user6',
    createdByName: 'Ngô Thị F',
    createdAt: '2026-02-26T14:00:00Z',
    updatedAt: '2026-02-26T14:00:00Z',
    isAnonymous: false,
    priority: 'medium',
    dueDate: '2026-03-10',
  },
  {
    id: 'sug4',
    title: 'Vấn đề thiếu giáo viên môn Tin học',
    content: 'Trường đang thiếu 2 giáo viên môn Tin học, ảnh hưởng đến chất lượng giảng dạy. Đề nghị Sở hỗ trợ bổ sung.',
    type: 'sensitive',
    status: 'assigned',
    category: 'Nhân sự',
    schoolId: '5',
    schoolName: 'Trường THPT Phan Đăng Lưu',
    departmentId: 'dept7',
    departmentName: 'Phòng Tổ chức Cán bộ',
    createdBy: 'user1',
    createdByName: 'Ẩn danh',
    createdAt: '2026-02-22T11:00:00Z',
    updatedAt: '2026-02-24T09:30:00Z',
    assignedTo: 'user3',
    assignedToName: 'Phạm Văn Y',
    isAnonymous: true,
    priority: 'high',
    dueDate: '2026-03-08',
  },
  {
    id: 'sug5',
    title: 'Đề nghị tổ chức bồi dưỡng nghiệp vụ cho giáo viên mầm non',
    content: 'Nhà trường mong muốn được tham gia các khóa bồi dưỡng về phương pháp giảng dạy mầm non theo chương trình mới.',
    type: 'sensitive',
    status: 'completed',
    category: 'Chuyên môn',
    schoolId: '4',
    schoolName: 'Trường Mầm non Hoa Mai',
    departmentId: 'dept1',
    departmentName: 'Phòng Giáo dục Mầm non',
    createdBy: 'user1',
    createdByName: 'Ẩn danh',
    createdAt: '2026-02-05T08:00:00Z',
    updatedAt: '2026-02-18T10:00:00Z',
    assignedTo: 'user3',
    assignedToName: 'Lê Thị Z',
    response: 'Phòng đã lên kế hoạch tổ chức khóa bồi dưỡng vào tháng 3/2026. Sẽ gửi thông báo chi tiết trong tuần tới.',
    isAnonymous: true,
    rating: 4,
    ratingComment: 'Hài lòng',
    priority: 'medium',
  },
  {
    id: 'sug6',
    title: 'Kiến nghị về việc điều chỉnh lịch thi học kỳ II',
    content: 'Do ảnh hưởng của dịch bệnh, đề nghị Sở xem xét điều chỉnh lại lịch thi học kỳ II để đảm bảo quyền lợi học sinh.',
    type: 'non-sensitive',
    status: 'rejected',
    category: 'Thi cử',
    schoolId: '1',
    schoolName: 'Trường THPT Huỳnh Thúc Kháng',
    departmentId: 'dept3',
    departmentName: 'Phòng Giáo dục Trung học',
    createdBy: 'user6',
    createdByName: 'Ngô Thị F',
    createdAt: '2026-02-18T15:00:00Z',
    updatedAt: '2026-02-20T11:00:00Z',
    response: 'Lịch thi đã được phê duyệt từ đầu năm học và kh��ng thể thay đổi. Trường vui lòng thực hiện theo kế hoạch.',
    isAnonymous: false,
    priority: 'low',
  },
];

// Mock FAQs
export const mockFAQs: FAQ[] = [
  {
    id: 'faq1',
    question: 'Quy trình xét duyệt kinh phí sửa chữa cơ sở vật chất như thế nào?',
    answer: 'Trường cần nộp hồ sơ bao gồm: 1) Tờ trình xin kinh phí, 2) Dự toán chi tiết, 3) Hình ảnh minh chứng. Phòng Tài chính sẽ thẩm định trong vòng 7 ngày làm việc.',
    category: 'Cơ sở vật chất',
    departmentId: 'dept6',
    departmentName: 'Phòng Tài chính và Đầu tư',
    isPublic: true,
    createdAt: '2026-01-15T10:00:00Z',
    views: 245,
  },
  {
    id: 'faq2',
    question: 'Thủ tục xin tuyển dụng giáo viên mới cần những gì?',
    answer: 'Trường cần có Tờ trình nêu rõ lý do thiếu giáo viên, môn học thiếu, số lượng cần tuyển. Gửi về Phòng TCCB trước ngày 15 hàng tháng.',
    category: 'Nhân sự',
    departmentId: 'dept7',
    departmentName: 'Phòng Tổ chức Cán bộ',
    isPublic: true,
    createdAt: '2026-01-20T09:00:00Z',
    views: 189,
  },
  {
    id: 'faq3',
    question: 'Làm sao để đăng ký tham gia thi học sinh giỏi cấp tỉnh?',
    answer: 'Trường đăng ký qua hệ thống quản lý thi cử của Sở từ ngày 1-15/3 hàng năm. Cần có danh sách học sinh, giáo viên hướng dẫn và văn bản đăng ký.',
    category: 'Thi cử',
    departmentId: 'dept4',
    departmentName: 'Phòng Quản lý Chất lượng',
    isPublic: true,
    createdAt: '2026-02-01T08:00:00Z',
    views: 312,
  },
  {
    id: 'faq4',
    question: 'Chế độ phụ cấp vùng khó khăn được tính như thế nào?',
    answer: 'Phụ cấp vùng khó khăn được tính theo Nghị định 73/2025 của Chính phủ, phân theo 4 mức tùy địa bàn. Chi tiết xem tại website của Sở.',
    category: 'Chế độ chính sách',
    departmentId: 'dept7',
    departmentName: 'Phòng Tổ chức Cán bộ',
    isPublic: true,
    createdAt: '2026-02-10T14:00:00Z',
    views: 428,
  },
];
